"""delete default datenow

Revision ID: 46bc479c8208
Revises: f9e10bf0c236
Create Date: 2026-03-30 19:32:06.758827

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "46bc479c8208"
down_revision: Union[str, Sequence[str], None] = "f9e10bf0c236"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
