"""fix1

Revision ID: a3cccc19425c
Revises: f6e7fdd51b23
Create Date: 2026-03-28 14:46:15.490784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3cccc19425c"
down_revision: Union[str, Sequence[str], None] = "f6e7fdd51b23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("place_id", sa.String(), nullable=False))
    op.create_foreign_key(None, "events", "places", ["place_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "events", type_="foreignkey")
    op.drop_column("events", "place_id")
    # ### end Alembic commands ###
