"""add relatoin

Revision ID: f6e7fdd51b23
Revises: 6c4578e45ede
Create Date: 2026-03-28 14:40:13.299375

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6e7fdd51b23"
down_revision: Union[str, Sequence[str], None] = "6c4578e45ede"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("events_place_fkey"), "events", type_="foreignkey")
    op.drop_column("events", "place")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("place", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        op.f("events_place_fkey"), "events", "places", ["place"], ["id"]
    )
    # ### end Alembic commands ###
