import typing

from src.domain.models import EventEntity, PlaceEntity


class EventProviderPort(typing.Protocol):
    async def get_events(self, url: str, date: str | None = None): ...
    async def get_available_seats(self, event_id: str): ...
    async def create_ticket(
        self, event_id: str, first_name: str, last_name: str, email: str, seat: str
    ): ...
    async def delete_ticket(self, event_id: str, ticket_id: str): ...
    async def iter_events(self, date_from: str) -> typing.AsyncIterator[list[dict]]: ...


class EventMapperPort(typing.Protocol):
    def map_events(self, event: EventEntity) -> EventEntity: ...
    def map_places(self, event: EventEntity) -> PlaceEntity: ...
