"""fix timezones

Revision ID: 23c01f66c241
Revises: a3cccc19425c
Create Date: 2026-03-28 16:14:21.770308

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "23c01f66c241"
down_revision: Union[str, Sequence[str], None] = "a3cccc19425c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
