"""fix id generating

Revision ID: 23f0e20e6678
Revises: 64786a97378c
Create Date: 2026-04-11 10:59:48.766282

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "23f0e20e6678"
down_revision: Union[str, Sequence[str], None] = "64786a97378c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
