"""add outbox

Revision ID: 64786a97378c
Revises: 0f07b836a3e8
Create Date: 2026-04-10 20:35:51.685981

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64786a97378c"
down_revision: Union[str, Sequence[str], None] = "0f07b836a3e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type_event", sa.Enum("buying", name="typeevent"), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column(
            "status", sa.Enum("awaits", "sent", name="outboxstatus"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outbox")
    # ### end Alembic commands ###
