"""del relation

Revision ID: 6c4578e45ede
Revises: b129e209c5ca
Create Date: 2026-03-28 14:34:00.751504

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c4578e45ede"
down_revision: Union[str, Sequence[str], None] = "b129e209c5ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("place", sa.String(), nullable=False))
    op.create_foreign_key(None, "events", "places", ["place"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "events", type_="foreignkey")
    op.drop_column("events", "place")
    # ### end Alembic commands ###
