"""add retry for outbox

Revision ID: 76146a0230b6
Revises: d267056d4aea
Create Date: 2026-04-13 11:40:05.650327

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76146a0230b6"
down_revision: Union[str, Sequence[str], None] = "d267056d4aea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("outbox", sa.Column("retry", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outbox", "retry")
    # ### end Alembic commands ###
