"""fix DateTime in BD models

Revision ID: 8685cf9bab7e
Revises: a2a9e8bf8c42
Create Date: 2026-04-12 11:34:24.865970

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "8685cf9bab7e"
down_revision: Union[str, Sequence[str], None] = "a2a9e8bf8c42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
