"""fix fault in name idem

Revision ID: a2a9e8bf8c42
Revises: e0d284e80c38
Create Date: 2026-04-12 11:12:47.390687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2a9e8bf8c42"
down_revision: Union[str, Sequence[str], None] = "e0d284e80c38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "idempotency_keys", sa.Column("ticket_id", sa.String(), nullable=True)
    )
    op.drop_column("idempotency_keys", "ticked_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "idempotency_keys",
        sa.Column("ticked_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("idempotency_keys", "ticket_id")
    # ### end Alembic commands ###
