"""add sync

Revision ID: b129e209c5ca
Revises: 3c7ed5d88a4a
Create Date: 2026-03-28 11:03:31.426199

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b129e209c5ca"
down_revision: Union[str, Sequence[str], None] = "3c7ed5d88a4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_status",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("last_sync_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sync_status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_status")
    # ### end Alembic commands ###
