import os

import dotenv

dotenv.load_dotenv()

# SERVER / AUTHORISATION
EVENTS_PROVIDER_SERVER = os.getenv("EVENTS_PROVIDER_SERVER_URL_OUTSIDE")
NOTIFY_PRIVIDER_SERVER = os.getenv("NOTIFY_PROVIDER_SERVER_URL_OUTSIDE")
EVENTS_PROVIDER_API_KEY = os.getenv("EVENTS_PROVIDER_API_KEY")
SENTRY_DSN = os.getenv("SENTRY_DSN")
